platform:ios,’11.0’
target 'imageViewer' do

inhibit_all_warnings!

pod 'YYWebImage'

pod 'MJExtension'

pod 'MJRefresh'

pod 'MBProgressHUD'

pod 'SJVideoPlayer'

pod 'SJBaseVideoPlayer'

pod 'Masonry'

end
