source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target 'LisApp' do

#tools
pod 'Alamofire'
pod 'Kingfisher'
pod 'YYWebImage'
pod 'HandyJSON', git: 'https://github.com/alibaba/HandyJSON.git' , branch: 'dev_for_swift5.0' 
pod 'MJRefresh'
pod 'SwiftyUserDefaults'
pod 'IQKeyboardManagerSwift'
pod 'SQLite.swift'
pod 'Hero'

#custom view
pod 'NVActivityIndicatorView'
pod 'TextFieldEffects'
pod 'CLImagePickerTool'
pod 'LTMorphingLabel'
pod 'Charts'

pod 'SJVideoPlayer'
pod 'SJBaseVideoPlayer'
pod 'Masonry'

end
